server:
  port: 8089

spring:
  application:
    name: reward-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reward-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.paypal.reward_service.entity.Transaction
        spring.kafka.consumer.properties.spring.json.use.type.headers: false
        spring.kafka.consumer.properties.spring.json.value.default.type: com.paypal.reward_service.entity.Transaction

    listener:
      missing-topics-fatal: false

  datasource:
    url: jdbc:h2:mem:reward_service_DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect